version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bus-trip-4320
    ports:
      - "5002:5000"
    volumes:
      - .:/project
    environment:
      FLASK_ENV: development
  db:
    image: mysql:latest
    container_name: bus-trip-db
    volumes: 
      - "./sql:/var/lib/bus-trip-mysql"
      - "./sql:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: dbpass
    ports:
      - "3306:3306"
    restart: always